var homophones = {
    "accessary": ['accessary', 'accessory'],
	"accessory": ['accessary', 'accessory'],
	"ad": ['ad', 'add'],
	"add": ['ad', 'add'],
	"ail": ['ail', 'ale'],
	"ale": ['ail', 'ale'],
	"air": ['air', 'heir'],
	"heir": ['air', 'heir'],
	"aisle": ['aisle', 'I-ll', 'isle'],
	"I-ll": ['aisle', 'I-ll', 'isle'],
	"isle": ['aisle', 'I-ll', 'isle'],
	"all": ['all', 'awl'],
	"awl": ['all', 'awl'],
	"allowed": ['allowed', 'aloud'],
	"aloud": ['allowed', 'aloud'],
	"alms": ['alms', 'arms'],
	"arms": ['alms', 'arms'],
	"altar": ['altar', 'alter'],
	"alter": ['altar', 'alter'],
	"arc": ['arc', 'ark'],
	"ark": ['arc', 'ark'],
	"aren-t": ['aren-t', 'aunt'],
	"aunt": ['aren-t', 'aunt'],
	"ate": ['ate', 'eight'],
	"eight": ['ate', 'eight'],
	"auger": ['auger', 'augur'],
	"augur": ['auger', 'augur'],
	"auk": ['auk', 'orc'],
	"orc": ['auk', 'orc'],
	"aural": ['aural', 'oral'],
	"oral": ['aural', 'oral'],
	"away": ['away', 'aweigh'],
	"aweigh": ['away', 'aweigh'],
	"awe": ['awe', 'oar', 'or', 'ore'],
	"oar": ['awe', 'oar', 'or', 'ore'],
	"or": ['awe', 'oar', 'or', 'ore'],
	"ore": ['awe', 'oar', 'or', 'ore'],
	"axel": ['axel', 'axle'],
	"axle": ['axel', 'axle'],
	"aye": ['aye', 'eye', 'I'],
	"eye": ['aye', 'eye', 'I'],
	"I": ['aye', 'eye', 'I'],
	"bail": ['bail', 'bale'],
	"bale": ['bail', 'bale'],
	"bait": ['bait', 'bate'],
	"bate": ['bait', 'bate'],
	"baize": ['baize', 'bays'],
	"bays": ['baize', 'bays'],
	"bald": ['bald', 'bawled'],
	"bawled": ['bald', 'bawled'],
	"ball": ['ball', 'bawl'],
	"bawl": ['ball', 'bawl'],
	"band": ['band', 'banned'],
	"banned": ['band', 'banned'],
	"bard": ['bard', 'barred'],
	"barred": ['bard', 'barred'],
	"bare": ['bare', 'bear'],
	"bear": ['bare', 'bear'],
	"bark": ['bark', 'barque'],
	"barque": ['bark', 'barque'],
	"baron": ['baron', 'barren'],
	"barren": ['baron', 'barren'],
	"base": ['base', 'bass'],
	"bass": ['base', 'bass'],
	"bay": ['bay', 'bey'],
	"bey": ['bay', 'bey'],
	"bazaar": ['bazaar', 'bizarre'],
	"bizarre": ['bazaar', 'bizarre'],
	"be": ['be', 'bee'],
	"bee": ['be', 'bee'],
	"beach": ['beach', 'beech'],
	"beech": ['beach', 'beech'],
	"bean": ['bean', 'been'],
	"been": ['bean', 'been'],
	"beat": ['beat', 'beet'],
	"beet": ['beat', 'beet'],
	"beau": ['beau', 'bow'],
	"bow": ['bough', 'bow'],
	"beer": ['beer', 'bier'],
	"bier": ['beer', 'bier'],
	"bel": ['bel', 'bell', 'belle'],
	"bell": ['bel', 'bell', 'belle'],
	"belle": ['bel', 'bell', 'belle'],
	"berry": ['berry', 'bury'],
	"bury": ['berry', 'bury'],
	"berth": ['berth', 'birth'],
	"birth": ['berth', 'birth'],
	"bight": ['bight', 'bite', 'byte'],
	"bite": ['bight', 'bite', 'byte'],
	"byte": ['bight', 'bite', 'byte'],
	"billed": ['billed', 'build'],
	"build": ['billed', 'build'],
	"bitten": ['bitten', 'bittern'],
	"bittern": ['bitten', 'bittern'],
	"blew": ['blew', 'blue'],
	"blue": ['blew', 'blue'],
	"bloc": ['bloc', 'block'],
	"block": ['bloc', 'block'],
	"boar": ['boar', 'bore'],
	"bore": ['boar', 'bore'],
	"board": ['board', 'bored'],
	"bored": ['board', 'bored'],
	"boarder": ['boarder', 'border'],
	"border": ['boarder', 'border'],
	"bold": ['bold', 'bowled'],
	"bowled": ['bold', 'bowled'],
	"boos": ['boos', 'booze'],
	"booze": ['boos', 'booze'],
	"born": ['born', 'borne'],
	"borne": ['born', 'borne'],
	"bough": ['bough', 'bow'],
	"boy": ['boy', 'buoy'],
	"buoy": ['boy', 'buoy'],
	"brae": ['brae', 'bray'],
	"bray": ['brae', 'bray'],
	"braid": ['braid', 'brayed'],
	"brayed": ['braid', 'brayed'],
	"braise": ['braise', 'brays', 'braze'],
	"brays": ['braise', 'brays', 'braze'],
	"braze": ['braise', 'brays', 'braze'],
	"brake": ['brake', 'break'],
	"break": ['brake', 'break'],
	"bread": ['bread', 'bred'],
	"bred": ['bread', 'bred'],
	"brews": ['brews', 'bruise'],
	"bruise": ['brews', 'bruise'],
	"bridal": ['bridal', 'bridle'],
	"bridle": ['bridal', 'bridle'],
	"broach": ['broach', 'brooch'],
	"brooch": ['broach', 'brooch'],
	"bur": ['bur', 'burr'],
	"burr": ['bur', 'burr'],
	"but": ['but', 'butt'],
	"butt": ['but', 'butt'],
	"buy": ['buy', 'by', 'bye'],
	"by": ['buy', 'by', 'bye'],
	"bye": ['buy', 'by', 'bye'],
	"buyer": ['buyer', 'byre'],
	"byre": ['buyer', 'byre'],
	"calendar": ['calendar', 'calender'],
	"calender": ['calendar', 'calender'],
	"call": ['call', 'caul'],
	"caul": ['call', 'caul'],
	"canvas": ['canvas', 'canvass'],
	"canvass": ['canvas', 'canvass'],
	"cast": ['cast', 'caste'],
	"caste": ['cast', 'caste'],
	"caster": ['caster', 'castor'],
	"castor": ['caster', 'castor'],
	"caught": ['caught', 'court'],
	"court": ['caught', 'court'],
	"caw": ['caw', 'core', 'corps'],
	"core": ['caw', 'core', 'corps'],
	"corps": ['caw', 'core', 'corps'],
	"cede": ['cede', 'seed'],
	"seed": ['cede', 'seed'],
	"ceiling": ['ceiling', 'sealing'],
	"sealing": ['ceiling', 'sealing'],
	"cell": ['cell', 'sell'],
	"sell": ['cell', 'sell'],
	"censer": ['censer', 'censor', 'sensor'],
	"censor": ['censer', 'censor', 'sensor'],
	"sensor": ['censer', 'censor', 'sensor'],
	"cent": ['cent', 'scent', 'sent'],
	"scent": ['cent', 'scent', 'sent'],
	"sent": ['cent', 'scent', 'sent'],
	"cereal": ['cereal', 'serial'],
	"serial": ['cereal', 'serial'],
	"cheap": ['cheap', 'cheep'],
	"cheep": ['cheap', 'cheep'],
	"check": ['check', 'cheque'],
	"cheque": ['check', 'cheque'],
	"choir": ['choir', 'quire'],
	"quire": ['choir', 'quire'],
	"chord": ['chord', 'cord'],
	"cord": ['chord', 'cord'],
	"cite": ['cite', 'sight', 'site'],
	"sight": ['cite', 'sight', 'site'],
	"site": ['cite', 'sight', 'site'],
	"clack": ['clack', 'claque'],
	"claque": ['clack', 'claque'],
	"clew": ['clew', 'clue'],
	"clue": ['clew', 'clue'],
	"climb": ['climb', 'clime'],
	"clime": ['climb', 'clime'],
	"close": ['close', 'cloze'],
	"cloze": ['close', 'cloze'],
	"coal": ['coal', 'kohl'],
	"kohl": ['coal', 'kohl'],
	"coarse": ['coarse', 'course'],
	"course": ['coarse', 'course'],
	"coign": ['coign', 'coin'],
	"coin": ['coign', 'coin'],
	"colonel": ['colonel', 'kernel'],
	"kernel": ['colonel', 'kernel'],
	"complacent": ['complacent', 'complaisant'],
	"complaisant": ['complacent', 'complaisant'],
	"complement": ['complement', 'compliment'],
	"compliment": ['complement', 'compliment'],
	"coo": ['coo', 'coup'],
	"coup": ['coo', 'coup'],
	"cops": ['cops', 'copse'],
	"copse": ['cops', 'copse'],
	"council": ['council', 'counsel'],
	"counsel": ['council', 'counsel'],
	"cousin": ['cousin', 'cozen'],
	"cozen": ['cousin', 'cozen'],
	"creak": ['creak', 'creek'],
	"creek": ['creak', 'creek'],
	"crews": ['crews', 'cruise'],
	"cruise": ['crews', 'cruise'],
	"cue": ['cue', 'kyu', 'queue'],
	"kyu": ['cue', 'kyu', 'queue'],
	"queue": ['cue', 'kyu', 'queue'],
	"curb": ['curb', 'kerb'],
	"kerb": ['curb', 'kerb'],
	"currant": ['currant', 'current'],
	"current": ['currant', 'current'],
	"cymbol": ['cymbol', 'symbol'],
	"symbol": ['cymbol', 'symbol'],
	"dam": ['dam', 'damn'],
	"damn": ['dam', 'damn'],
	"days": ['days', 'daze'],
	"daze": ['days', 'daze'],
	"dear": ['dear', 'deer'],
	"deer": ['dear', 'deer'],
	"descent": ['descent', 'dissent'],
	"dissent": ['descent', 'dissent'],
	"desert": ['desert', 'dessert'],
	"dessert": ['desert', 'dessert'],
	"deviser": ['deviser', 'divisor'],
	"divisor": ['deviser', 'divisor'],
	"dew": ['dew', 'due'],
	"due": ['dew', 'due'],
	"die": ['die', 'dye'],
	"dye": ['die', 'dye'],
	"discreet": ['discreet', 'discrete'],
	"discrete": ['discreet', 'discrete'],
	"doe": ['doe', 'doh', 'dough'],
	"doh": ['doe', 'doh', 'dough'],
	"dough": ['doe', 'doh', 'dough'],
	"done": ['done', 'dun'],
	"dun": ['done', 'dun'],
	"douse": ['douse', 'dowse'],
	"dowse": ['douse', 'dowse'],
	"draft": ['draft', 'draught'],
	"draught": ['draft', 'draught'],
	"dual": ['dual', 'duel'],
	"duel": ['dual', 'duel'],
	"earn": ['earn', 'urn'],
	"urn": ['earn', 'urn'],
	"eery": ['eery', 'eyrie'],
	"eyrie": ['eery', 'eyrie'],
	"ewe": ['ewe', 'yew', 'you'],
	"yew": ['ewe', 'yew', 'you'],
	"you": ['ewe', 'yew', 'you'],
	"faint": ['faint', 'feint'],
	"feint": ['faint', 'feint'],
	"fah": ['fah', 'far'],
	"far": ['fah', 'far'],
	"fair": ['fair', 'fare'],
	"fare": ['fair', 'fare'],
	"farther": ['farther', 'father'],
	"father": ['farther', 'father'],
	"fate": ['fate', 'fÃªte'],
	"fÃªte": ['fate', 'fÃªte'],
	"faun": ['faun', 'fawn'],
	"fawn": ['faun', 'fawn'],
	"fay": ['fay', 'fey'],
	"fey": ['fay', 'fey'],
	"faze": ['faze', 'phase'],
	"phase": ['faze', 'phase'],
	"feat": ['feat', 'feet'],
	"feet": ['feat', 'feet'],
	"ferrule": ['ferrule', 'ferule'],
	"ferule": ['ferrule', 'ferule'],
	"few": ['few', 'phew'],
	"phew": ['few', 'phew'],
	"fie": ['fie', 'phi'],
	"phi": ['fie', 'phi'],
	"file": ['file', 'phial'],
	"phial": ['file', 'phial'],
	"find": ['find', 'fined'],
	"fined": ['find', 'fined'],
	"fir": ['fir', 'fur'],
	"fur": ['fir', 'fur'],
	"fizz": ['fizz', 'phiz'],
	"phiz": ['fizz', 'phiz'],
	"flair": ['flair', 'flare'],
	"flare": ['flair', 'flare'],
	"flaw": ['flaw', 'floor'],
	"floor": ['flaw', 'floor'],
	"flea": ['flea', 'flee'],
	"flee": ['flea', 'flee'],
	"flex": ['flex', 'flecks'],
	"flecks": ['flex', 'flecks'],
	"flew": ['flew', 'flu', 'flue'],
	"flu": ['flew', 'flu', 'flue'],
	"flue": ['flew', 'flu', 'flue'],
	"floe": ['floe', 'flow'],
	"flow": ['floe', 'flow'],
	"flour": ['flour', 'flower'],
	"flower": ['flour', 'flower'],
	"foaled": ['foaled', 'fold'],
	"fold": ['foaled', 'fold'],
	"for": ['for', 'fore', 'four'],
	"fore": ['for', 'fore', 'four'],
	"four": ['for', 'fore', 'four'],
	"foreword": ['foreword', 'forward'],
	"forward": ['foreword', 'forward'],
	"fort": ['fort', 'fought'],
	"fought": ['fort', 'fought'],
	"forth": ['forth', 'fourth'],
	"fourth": ['forth', 'fourth'],
	"foul": ['foul', 'fowl'],
	"fowl": ['foul', 'fowl'],
	"franc": ['franc', 'frank'],
	"frank": ['franc', 'frank'],
	"freeze": ['freeze', 'frieze'],
	"frieze": ['freeze', 'frieze'],
	"friar": ['friar', 'fryer'],
	"fryer": ['friar', 'fryer'],
	"furs": ['furs', 'furze'],
	"furze": ['furs', 'furze'],
	"gait": ['gait', 'gate'],
	"gate": ['gait', 'gate'],
	"galipot": ['galipot', 'gallipot'],
	"gallipot": ['galipot', 'gallipot'],
	"gallop": ['gallop', 'galop'],
	"galop": ['gallop', 'galop'],
	"gamble": ['gamble', 'gambol'],
	"gambol": ['gamble', 'gambol'],
	"gays": ['gays', 'gaze'],
	"gaze": ['gays', 'gaze'],
	"genes": ['genes', 'jeans'],
	"jeans": ['genes', 'jeans'],
	"gild": ['gild', 'guild'],
	"guild": ['gild', 'guild'],
	"gilt": ['gilt', 'guilt'],
	"guilt": ['gilt', 'guilt'],
	"giro": ['giro', 'gyro'],
	"gyro": ['giro', 'gyro'],
	"gnaw": ['gnaw', 'nor'],
	"nor": ['gnaw', 'nor'],
	"gneiss": ['gneiss', 'nice'],
	"nice": ['gneiss', 'nice'],
	"gorilla": ['gorilla', 'guerilla'],
	"guerilla": ['gorilla', 'guerilla'],
	"grate": ['grate', 'great'],
	"great": ['grate', 'great'],
	"greave": ['greave', 'grieve'],
	"grieve": ['greave', 'grieve'],
	"greys": ['greys', 'graze'],
	"graze": ['greys', 'graze'],
	"grisly": ['grisly', 'grizzly'],
	"grizzly": ['grisly', 'grizzly'],
	"groan": ['groan', 'grown'],
	"grown": ['groan', 'grown'],
	"guessed": ['guessed', 'guest'],
	"guest": ['guessed', 'guest'],
	"hail": ['hail', 'hale'],
	"hale": ['hail', 'hale'],
	"hair": ['hair', 'hare'],
	"hare": ['hair', 'hare'],
	"hall": ['hall', 'haul'],
	"haul": ['hall', 'haul'],
	"hangar": ['hangar', 'hanger'],
	"hanger": ['hangar', 'hanger'],
	"hart": ['hart', 'heart'],
	"heart": ['hart', 'heart'],
	"haw": ['haw', 'hoar', 'whore'],
	"hoar": ['haw', 'hoar', 'whore'],
	"whore": ['haw', 'hoar', 'whore'],
	"hay": ['hay', 'hey'],
	"hey": ['hay', 'hey'],
	"heal": ['heal', 'heel', 'he-ll'],
	"heel": ['heal', 'heel', 'he-ll'],
	"he-ll": ['heal', 'heel', 'he-ll'],
	"hear": ['hear', 'here'],
	"here": ['hear', 'here'],
	"heard": ['heard', 'herd'],
	"herd": ['heard', 'herd'],
	"he-d": ['he-d', 'heed'],
	"heed": ['he-d', 'heed'],
	"heroin": ['heroin', 'heroine'],
	"heroine": ['heroin', 'heroine'],
	"hew": ['hew', 'hue'],
	"hue": ['hew', 'hue'],
	"hi": ['hi', 'high'],
	"high": ['hi', 'high'],
	"higher": ['higher', 'hire'],
	"hire": ['higher', 'hire'],
	"him": ['him', 'hymn'],
	"hymn": ['him', 'hymn'],
	"ho": ['ho', 'hoe'],
	"hoe": ['ho', 'hoe'],
	"hoard": ['hoard', 'horde'],
	"horde": ['hoard', 'horde'],
	"hoarse": ['hoarse', 'horse'],
	"horse": ['hoarse', 'horse'],
	"holey": ['holey', 'holy', 'wholly'],
	"holy": ['holey', 'holy', 'wholly'],
	"wholly": ['holey', 'holy', 'wholly'],
	"hour": ['hour', 'our'],
	"our": ['hour', 'our'],
	"idle": ['idle', 'idol'],
	"idol": ['idle', 'idol'],
	"in": ['in', 'inn'],
	"inn": ['in', 'inn'],
	"indict": ['indict', 'indite'],
	"indite": ['indict', 'indite'],
	"it-s": ['it-s', 'its'],
	"its": ['it-s', 'its'],
	"jewel": ['jewel', 'joule'],
	"joule": ['jewel', 'joule'],
	"key": ['key', 'quay'],
	"quay": ['key', 'quay'],
	"knave": ['knave', 'nave'],
	"nave": ['knave', 'nave'],
	"knead": ['knead', 'need'],
	"need": ['knead', 'need'],
	"knew": ['knew', 'new'],
	"new": ['knew', 'new'],
	"knight": ['knight', 'night'],
	"night": ['knight', 'night'],
	"knit": ['knit', 'nit'],
	"nit": ['knit', 'nit'],
	"knob": ['knob', 'nob'],
	"nob": ['knob', 'nob'],
	"knock": ['knock', 'nock'],
	"nock": ['knock', 'nock'],
	"knot": ['knot', 'not'],
	"not": ['knot', 'not'],
	"know": ['know', 'no'],
	"no": ['know', 'no'],
	"knows": ['knows', 'nose'],
	"nose": ['knows', 'nose'],
	"laager": ['laager', 'lager'],
	"lager": ['laager', 'lager'],
	"lac": ['lac', 'lack'],
	"lack": ['lac', 'lack'],
	"lade": ['lade', 'laid'],
	"laid": ['lade', 'laid'],
	"lain": ['lain', 'lane'],
	"lane": ['lain', 'lane'],
	"lam": ['lam', 'lamb'],
	"lamb": ['lam', 'lamb'],
	"laps": ['laps', 'lapse'],
	"lapse": ['laps', 'lapse'],
	"larva": ['larva', 'lava'],
	"lava": ['larva', 'lava'],
	"lase": ['lase', 'laze'],
	"laze": ['lase', 'laze'],
	"law": ['law', 'lore'],
	"lore": ['law', 'lore'],
	"lay": ['lay', 'ley'],
	"ley": ['lay', 'ley'],
	"lea": ['lea', 'lee'],
	"lee": ['lea', 'lee'],
	"leach": ['leach', 'leech'],
	"leech": ['leach', 'leech'],
	"lead": ['lead', 'led'],
	"led": ['lead', 'led'],
	"leak": ['leak', 'leek'],
	"leek": ['leak', 'leek'],
	"lean": ['lean', 'lien'],
	"lien": ['lean', 'lien'],
	"lessen": ['lessen', 'lesson'],
	"lesson": ['lessen', 'lesson'],
	"levee": ['levee', 'levy'],
	"levy": ['levee', 'levy'],
	"liar": ['liar', 'lyre'],
	"lyre": ['liar', 'lyre'],
	"licence": ['licence', 'license'],
	"license": ['licence', 'license'],
	"licker": ['licker', 'liquor'],
	"liquor": ['licker', 'liquor'],
	"lie": ['lie', 'lye'],
	"lye": ['lie', 'lye'],
	"lieu": ['lieu', 'loo'],
	"loo": ['lieu', 'loo'],
	"links": ['links', 'lynx'],
	"lynx": ['links', 'lynx'],
	"lo": ['lo', 'low'],
	"low": ['lo', 'low'],
	"load": ['load', 'lode'],
	"lode": ['load', 'lode'],
	"loan": ['loan', 'lone'],
	"lone": ['loan', 'lone'],
	"locks": ['locks', 'lox'],
	"lox": ['locks', 'lox'],
	"loop": ['loop', 'loupe'],
	"loupe": ['loop', 'loupe'],
	"loot": ['loot', 'lute'],
	"lute": ['loot', 'lute'],
	"made": ['made', 'maid'],
	"maid": ['made', 'maid'],
	"mail": ['mail', 'male'],
	"male": ['mail', 'male'],
	"main": ['main', 'mane'],
	"mane": ['main', 'mane'],
	"maize": ['maize', 'maze'],
	"maze": ['maize', 'maze'],
	"mall": ['mall', 'maul'],
	"maul": ['mall', 'maul'],
	"manna": ['manna', 'manner'],
	"manner": ['manna', 'manner'],
	"mantel": ['mantel', 'mantle'],
	"mantle": ['mantel', 'mantle'],
	"mare": ['mare', 'mayor'],
	"mayor": ['mare', 'mayor'],
	"mark": ['mark', 'marque'],
	"marque": ['mark', 'marque'],
	"marshal": ['marshal', 'martial'],
	"martial": ['marshal', 'martial'],
	"marten": ['marten', 'martin'],
	"martin": ['marten', 'martin'],
	"mask": ['mask', 'masque'],
	"masque": ['mask', 'masque'],
	"maw": ['maw', 'more'],
	"more": ['moor', 'more'],
	"me": ['me', 'mi'],
	"mi": ['me', 'mi'],
	"mean": ['mean', 'mien'],
	"mien": ['mean', 'mien'],
	"meat": ['meat', 'meet', 'mete'],
	"meet": ['meat', 'meet', 'mete'],
	"mete": ['meat', 'meet', 'mete'],
	"medal": ['medal', 'meddle'],
	"meddle": ['medal', 'meddle'],
	"metal": ['metal', 'mettle'],
	"mettle": ['metal', 'mettle'],
	"meter": ['meter', 'metre'],
	"metre": ['meter', 'metre'],
	"might": ['might', 'mite'],
	"mite": ['might', 'mite'],
	"miner": ['miner', 'minor', 'mynah'],
	"minor": ['miner', 'minor', 'mynah'],
	"mynah": ['miner', 'minor', 'mynah'],
	"mind": ['mind', 'mined'],
	"mined": ['mind', 'mined'],
	"missed": ['missed', 'mist'],
	"mist": ['missed', 'mist'],
	"moat": ['moat', 'mote'],
	"mote": ['moat', 'mote'],
	"mode": ['mode', 'mowed'],
	"mowed": ['mode', 'mowed'],
	"moor": ['moor', 'more'],
	"moose": ['moose', 'mousse'],
	"mousse": ['moose', 'mousse'],
	"morning": ['morning', 'mourning'],
	"mourning": ['morning', 'mourning'],
	"muscle": ['muscle', 'mussel'],
	"mussel": ['muscle', 'mussel'],
	"naval": ['naval', 'navel'],
	"navel": ['naval', 'navel'],
	"nay": ['nay', 'neigh'],
	"neigh": ['nay', 'neigh'],
	"nigh": ['nigh', 'nye'],
	"nye": ['nigh', 'nye'],
	"none": ['none', 'nun'],
	"nun": ['none', 'nun'],
	"od": ['od', 'odd'],
	"odd": ['od', 'odd'],
	"ode": ['ode', 'owed'],
	"owed": ['ode', 'owed'],
	"oh": ['oh', 'owe'],
	"owe": ['oh', 'owe'],
	"one": ['one', 'won'],
	"won": ['one', 'won'],
	"packed": ['packed', 'pact'],
	"pact": ['packed', 'pact'],
	"packs": ['packs', 'pax'],
	"pax": ['packs', 'pax'],
	"pail": ['pail', 'pale'],
	"pale": ['pail', 'pale'],
	"pain": ['pain', 'pane'],
	"pane": ['pain', 'pane'],
	"pair": ['pair', 'pare', 'pear'],
	"pare": ['pair', 'pare', 'pear'],
	"pear": ['pair', 'pare', 'pear'],
	"palate": ['palate', 'palette', 'pallet'],
	"palette": ['palate', 'palette', 'pallet'],
	"pallet": ['palate', 'palette', 'pallet'],
	"pascal": ['pascal', 'paschal'],
	"paschal": ['pascal', 'paschal'],
	"paten": ['paten', 'patten', 'pattern'],
	"patten": ['paten', 'patten', 'pattern'],
	"pattern": ['paten', 'patten', 'pattern'],
	"pause": ['pause', 'paws', 'pores', 'pours'],
	"paws": ['pause', 'paws', 'pores', 'pours'],
	"pores": ['pause', 'paws', 'pores', 'pours'],
	"pours": ['pause', 'paws', 'pores', 'pours'],
	"pawn": ['pawn', 'porn'],
	"porn": ['pawn', 'porn'],
	"pea": ['pea', 'pee'],
	"pee": ['pea', 'pee'],
	"peace": ['peace', 'piece'],
	"piece": ['peace', 'piece'],
	"peak": ['peak', 'peek', 'peke', 'pique'],
	"peek": ['peak', 'peek', 'peke', 'pique'],
	"peke": ['peak', 'peek', 'peke', 'pique'],
	"pique": ['peak', 'peek', 'peke', 'pique'],
	"peal": ['peal', 'peel'],
	"peel": ['peal', 'peel'],
	"pearl": ['pearl', 'purl'],
	"purl": ['pearl', 'purl'],
	"pedal": ['pedal', 'peddle'],
	"peddle": ['pedal', 'peddle'],
	"peer": ['peer', 'pier'],
	"pier": ['peer', 'pier'],
	"pi": ['pi', 'pie'],
	"pie": ['pi', 'pie'],
	"pica": ['pica', 'pika'],
	"pika": ['pica', 'pika'],
	"place": ['place', 'plaice'],
	"plaice": ['place', 'plaice'],
	"plain": ['plain', 'plane'],
	"plane": ['plain', 'plane'],
	"pleas": ['pleas', 'please'],
	"please": ['pleas', 'please'],
	"plum": ['plum', 'plumb'],
	"plumb": ['plum', 'plumb'],
	"pole": ['pole', 'poll'],
	"poll": ['pole', 'poll'],
	"poof": ['poof', 'pouffe'],
	"pouffe": ['poof', 'pouffe'],
	"practice": ['practice', 'practise'],
	"practise": ['practice', 'practise'],
	"praise": ['praise', 'prays', 'preys'],
	"prays": ['praise', 'prays', 'preys'],
	"preys": ['praise', 'prays', 'preys'],
	"principal": ['principal', 'principle'],
	"principle": ['principal', 'principle'],
	"profit": ['profit', 'prophet'],
	"prophet": ['profit', 'prophet'],
	"quarts": ['quarts', 'quartz'],
	"quartz": ['quarts', 'quartz'],
	"quean": ['quean', 'queen'],
	"queen": ['quean', 'queen'],
	"rain": ['rain', 'reign', 'rein'],
	"reign": ['rain', 'reign', 'rein'],
	"rein": ['rain', 'reign', 'rein'],
	"raise": ['raise', 'rays', 'raze'],
	"rays": ['raise', 'rays', 'raze'],
	"raze": ['raise', 'rays', 'raze'],
	"rap": ['rap', 'wrap'],
	"wrap": ['rap', 'wrap'],
	"raw": ['raw', 'roar'],
	"roar": ['raw', 'roar'],
	"read": ['read', 'red'],
	"reed": ['read', 'reed'],
	"red": ['read', 'red'],
	"real": ['real', 'reel'],
	"reel": ['real', 'reel'],
	"reek": ['reek', 'wreak'],
	"wreak": ['reek', 'wreak'],
	"rest": ['rest', 'wrest'],
	"wrest": ['rest', 'wrest'],
	"retch": ['retch', 'wretch'],
	"wretch": ['retch', 'wretch'],
	"review": ['review', 'revue'],
	"revue": ['review', 'revue'],
	"rheum": ['rheum', 'room'],
	"room": ['rheum', 'room'],
	"right": ['right', 'rite', 'wright', 'write'],
	"rite": ['right', 'rite', 'wright', 'write'],
	"wright": ['right', 'rite', 'wright', 'write'],
	"write": ['right', 'rite', 'wright', 'write'],
	"ring": ['ring', 'wring'],
	"wring": ['ring', 'wring'],
	"road": ['road', 'rode'],
	"rode": ['road', 'rode'],
	"roe": ['roe', 'row'],
	"row": ['roe', 'row'],
	"role": ['role', 'roll'],
	"roll": ['role', 'roll'],
	"roo": ['roo', 'roux', 'rue'],
	"roux": ['roo', 'roux', 'rue'],
	"rue": ['roo', 'roux', 'rue'],
	"rood": ['rood', 'rude'],
	"rude": ['rood', 'rude'],
	"root": ['root', 'route'],
	"route": ['root', 'route'],
	"rose": ['rose', 'rows'],
	"rows": ['rouse', 'rows'],
	"rota": ['rota', 'rotor'],
	"rotor": ['rota', 'rotor'],
	"rote": ['rote', 'wrote'],
	"wrote": ['rote', 'wrote'],
	"rough": ['rough', 'ruff'],
	"ruff": ['rough', 'ruff'],
	"rouse": ['rouse', 'rows'],
	"rung": ['rung', 'wrung'],
	"wrung": ['rung', 'wrung'],
	"rye": ['rye', 'wry'],
	"wry": ['rye', 'wry'],
	"saver": ['saver', 'savour'],
	"savour": ['saver', 'savour'],
	"spade": ['spade', 'spayed'],
	"spayed": ['spade', 'spayed'],
	"sale": ['sale', 'sail'],
	"sail": ['sale', 'sail'],
	"sane": ['sane', 'seine'],
	"seine": ['sane', 'seine'],
	"satire": ['satire', 'satyr'],
	"satyr": ['satire', 'satyr'],
	"sauce": ['sauce', 'source'],
	"source": ['sauce', 'source'],
	"saw": ['saw', 'soar', 'sore'],
	"soar": ['saw', 'soar', 'sore'],
	"sore": ['saw', 'soar', 'sore'],
	"scene": ['scene', 'seen'],
	"seen": ['scene', 'seen'],
	"scull": ['scull', 'skull'],
	"skull": ['scull', 'skull'],
	"sea": ['sea', 'see'],
	"see": ['sea', 'see'],
	"seam": ['seam', 'seem'],
	"seem": ['seam', 'seem'],
	"sear": ['sear', 'seer', 'sere'],
	"seer": ['sear', 'seer', 'sere'],
	"sere": ['sear', 'seer', 'sere'],
	"seas": ['seas', 'sees', 'seize'],
	"sees": ['seas', 'sees', 'seize'],
	"seize": ['seas', 'sees', 'seize'],
	"sew": ['sew', 'so', 'sow'],
	"so": ['sew', 'so', 'sow'],
	"sow": ['sew', 'so', 'sow'],
	"shake": ['shake', 'sheikh'],
	"sheikh": ['shake', 'sheikh'],
	"shear": ['shear', 'sheer'],
	"sheer": ['shear', 'sheer'],
	"shoe": ['shoe', 'shoo'],
	"shoo": ['shoe', 'shoo'],
	"sic": ['sic', 'sick'],
	"sick": ['sic', 'sick'],
	"side": ['side', 'sighed'],
	"sighed": ['side', 'sighed'],
	"sign": ['sign', 'sine'],
	"sine": ['sign', 'sine'],
	"sink": ['sink', 'synch'],
	"synch": ['sink', 'synch'],
	"slay": ['slay', 'sleigh'],
	"sleigh": ['slay', 'sleigh'],
	"sloe": ['sloe', 'slow'],
	"slow": ['sloe', 'slow'],
	"sole": ['sole', 'soul'],
	"soul": ['sole', 'soul'],
	"some": ['some', 'sum'],
	"sum": ['some', 'sum'],
	"son": ['son', 'sun'],
	"sun": ['son', 'sun'],
	"sort": ['sort', 'sought'],
	"sought": ['sort', 'sought'],
	"spa": ['spa', 'spar'],
	"spar": ['spa', 'spar'],
	"staid": ['staid', 'stayed'],
	"stayed": ['staid', 'stayed'],
	"stair": ['stair', 'stare'],
	"stare": ['stair', 'stare'],
	"stake": ['stake', 'steak'],
	"steak": ['stake', 'steak'],
	"stalk": ['stalk', 'stork'],
	"stork": ['stalk', 'stork'],
	"stationary": ['stationary', 'stationery'],
	"stationery": ['stationary', 'stationery'],
	"steal": ['steal', 'steel'],
	"steel": ['steal', 'steel'],
	"stile": ['stile', 'style'],
	"style": ['stile', 'style'],
	"storey": ['storey', 'story'],
	"story": ['storey', 'story'],
	"straight": ['straight', 'strait'],
	"strait": ['straight', 'strait'],
	"sweet": ['sweet', 'suite'],
	"suite": ['sweet', 'suite'],
	"swat": ['swat', 'swot'],
	"swot": ['swat', 'swot'],
	"tacks": ['tacks', 'tax'],
	"tax": ['tacks', 'tax'],
	"tale": ['tale', 'tail'],
	"tail": ['tale', 'tail'],
	"talk": ['talk', 'torque'],
	"torque": ['talk', 'torque'],
	"tare": ['tare', 'tear'],
	"tear": ['tear', 'tier'],
	"taught": ['taught', 'taut', 'tort'],
	"taut": ['taught', 'taut', 'tort'],
	"tort": ['taught', 'taut', 'tort'],
	"te": ['te', 'tea', 'tee'],
	"tea": ['te', 'tea', 'tee'],
	"tee": ['te', 'tea', 'tee'],
	"team": ['team', 'teem'],
	"teem": ['team', 'teem'],
	"tier": ['tear', 'tier'],
	"teas": ['teas', 'tease'],
	"tease": ['teas', 'tease'],
	"terce": ['terce', 'terse'],
	"terse": ['terce', 'terse'],
	"tern": ['tern', 'turn'],
	"turn": ['tern', 'turn'],
	"there": ['there', 'their', 'they-re'],
	"their": ['there', 'their', 'they-re'],
	"they-re": ['there', 'their', 'they-re'],
	"threw": ['threw', 'through'],
	"through": ['threw', 'through'],
	"throes": ['throes', 'throws'],
	"throws": ['throes', 'throws'],
	"throne": ['throne', 'thrown'],
	"thrown": ['throne', 'thrown'],
	"thyme": ['thyme', 'time'],
	"time": ['thyme', 'time'],
	"tic": ['tic', 'tick'],
	"tick": ['tic', 'tick'],
	"tide": ['tide', 'tied'],
	"tied": ['tide', 'tied'],
	"tire": ['tire', 'tyre'],
	"tyre": ['tire', 'tyre'],
	"to": ['to', 'too', 'two'],
	"too": ['to', 'too', 'two'],
	"two": ['to', 'too', 'two'],
	"toad": ['toad', 'toed', 'towed'],
	"toed": ['toad', 'toed', 'towed'],
	"towed": ['toad', 'toed', 'towed'],
	"told": ['told', 'tolled'],
	"tolled": ['told', 'tolled'],
	"tole": ['tole', 'toll'],
	"toll": ['tole', 'toll'],
	"ton": ['ton', 'tun'],
	"tun": ['ton', 'tun'],
	"tor": ['tor', 'tore'],
	"tore": ['tor', 'tore'],
	"tough": ['tough', 'tuff'],
	"tuff": ['tough', 'tuff'],
	"troop": ['troop', 'troupe'],
	"troupe": ['troop', 'troupe'],
	"tuba": ['tuba', 'tuber'],
	"tuber": ['tuba', 'tuber'],
	"vain": ['vain', 'vane', 'vein'],
	"vane": ['vain', 'vane', 'vein'],
	"vein": ['vain', 'vane', 'vein'],
	"vale": ['vale', 'veil'],
	"veil": ['vale', 'veil'],
	"vial": ['vial', 'vile'],
	"vile": ['vial', 'vile'],
	"wail": ['wail', 'wale', 'whale'],
	"wale": ['wail', 'wale', 'whale'],
	"whale": ['wail', 'wale', 'whale'],
	"wain": ['wain', 'wane'],
	"wane": ['wain', 'wane'],
	"waist": ['waist', 'waste'],
	"waste": ['waist', 'waste'],
	"wait": ['wait', 'weight'],
	"weight": ['wait', 'weight'],
	"waive": ['waive', 'wave'],
	"wave": ['waive', 'wave'],
	"wall": ['wall', 'waul'],
	"waul": ['wall', 'waul'],
	"war": ['war', 'wore'],
	"wore": ['war', 'wore'],
	"ware": ['ware', 'wear', 'where'],
	"wear": ['ware', 'wear', 'where'],
	"where": ['ware', 'wear', 'where'],
	"warn": ['warn', 'worn'],
	"worn": ['warn', 'worn'],
	"wart": ['wart', 'wort'],
	"wort": ['wart', 'wort'],
	"watt": ['watt', 'what'],
	"what": ['watt', 'what'],
	"wax": ['wax', 'whacks'],
	"whacks": ['wax', 'whacks'],
	"way": ['way', 'weigh', 'whey'],
	"weigh": ['way', 'weigh', 'whey'],
	"whey": ['way', 'weigh', 'whey'],
	"we": ['we', 'wee', 'whee'],
	"wee": ['we', 'wee', 'whee'],
	"whee": ['we', 'wee', 'whee'],
	"weak": ['weak', 'week'],
	"week": ['weak', 'week'],
	"we-d": ['we-d', 'weed'],
	"weed": ['we-d', 'weed'],
	"weal": ['weal', 'we-ll', 'wheel'],
	"we-ll": ['weal', 'we-ll', 'wheel'],
	"wheel": ['weal', 'we-ll', 'wheel'],
	"wean": ['wean', 'ween'],
	"ween": ['wean', 'ween'],
	"weather": ['weather', 'whether'],
	"whether": ['weather', 'whether'],
	"weaver": ['weaver', 'weever'],
	"weever": ['weaver', 'weever'],
	"weir": ['weir', 'we-re'],
	"we-re": ['weir', 'we-re'],
	"were": ['were', 'whirr'],
	"whirr": ['were', 'whirr'],
	"wet": ['wet', 'whet'],
	"whet": ['wet', 'whet'],
	"wheald": ['wheald', 'wheeled'],
	"wheeled": ['wheald', 'wheeled'],
	"which": ['which', 'witch'],
	"witch": ['which', 'witch'],
	"whig": ['whig', 'wig'],
	"wig": ['whig', 'wig'],
	"while": ['while', 'wile'],
	"wile": ['while', 'wile'],
	"whine": ['whine', 'wine'],
	"wine": ['whine', 'wine'],
	"whirl": ['whirl', 'whorl'],
	"whorl": ['whirl', 'whorl'],
	"whirled": ['whirled', 'world'],
	"world": ['whirled', 'world'],
	"whit": ['whit', 'wit'],
	"wit": ['whit', 'wit'],
	"white": ['white', 'wight'],
	"wight": ['white', 'wight'],
	"who-s": ['who-s', 'whose'],
	"whose": ['who-s', 'whose'],
	"woe": ['woe', 'whoa'],
	"whoa": ['woe', 'whoa'],
	"wood": ['wood', 'would'],
	"would": ['wood', 'would'],
	"yaw": ['yaw', 'yore', 'your', 'you-re'],
	"yore": ['yaw', 'yore', 'your', 'you-re'],
	"your": ['yaw', 'yore', 'your', 'you-re'],
	"you-re": ['yaw', 'yore', 'your', 'you-re'],
	"yoke": ['yoke', 'yolk'],
	"yolk": ['yoke', 'yolk'],
	"you-ll": ['you-ll', 'yule'],
	"yule": ['you-ll', 'yule']
};
